### ISSUE TITLE
Questions about output

### ISSUE THREAD

**Issue by Yeager-101** [brucecai-2001/torch-RT-1#1]
Hello, thank you very much for your work. I noticed that in the code, `action_token_len=8` means only the output of the robot arm. If I want the normal 11 parameter output now, how should I modify your code?

**Comment by brucecai-2001** [comment]
Hi, thank you for your feedback. If I understand correctly, I think the simplest way is to set `action_token_len  = 11`. However in my implementation this will also make the learnt token in the token_learner to 11. You may also need to rewrite the action tokenizer.

**Comment by brucecai-2001** [comment]
Hi, thank you for your feedback. If I understand correctly, I think the simplest way is to set action_token_len  = 11 in RT1. However in my implementation this will also make the learnt token in the token_learner to 11. You may also need to rewrite the action tokenizer.

**Comment by Yeager-101** [comment]
> action_token_len = 11

I also thought about changing the 'action_token_len=8' in '__init__' under 'class RT1(BaseModel):' to 'action_token_len=11', but I didn't think of modifying the action tokenizer. I understand the action tokenizer as the content in 'action_tokenize.py', but I noticed that you seemed to have commented out this part of the code in RT1:
![2024-08-20 08-47-48 的屏幕截图](https://github.com/user-attachments/assets/c6a12148-8617-400d-8dd6-6e3be94bab7c)

Why is this the case, and how should I modify it specifically? I'm sorry that I'm a novice in this area.
